### ISSUE TITLE
archive?

### ISSUE THREAD

**Issue by geoffrey-vl** [mossblaser/aiomqtt#13]
since pypi has dropped this repo, shouldn't this repo be archived in favor of https://github.com/sbtinstruments/aiomqtt?

**Comment by mossblaser** [comment]
Hello there,

I'm waiting for the new owners to sort out the version numbering issue and will put up an update...

The plan was to keep this old project on minimal maintenance only with any new versions necessary being debug point releases <1.0.0. Alas the new project have confused matters by pushing a <1.0.0 release by accident. Hopefully this will be resolved soon.

Sorry about the confusion...

Jonathan

**Comment by mossblaser** [comment]
I believe the accidental v0.17 release on PyPI has now been yanked and I've now added a note to the repo about the naming situation.

As stated above, I don't plan to archive the repo since I intend to continue with essential maintenance of this original project since I (like presumably others) still have software built on top of it.
