### ISSUE TITLE
Why dont you have a consistency with subscribe and publish? 

### ISSUE THREAD

**Issue by vladyslav2** [mossblaser/aiomqtt#2]
You have defined on_subscribe and use `await subscribed.wait()` with for subscribe:
```
    subscribed = asyncio.Event(loop=loop)
    def on_subscribe(client, userdata, mid, granted_qos):
        subscribed.set()
    c.on_subscribe = on_subscribe
    
    c.subscribe("my/test/path")
    await subscribed.wait()
    print("Subscribed to my/test/path")
```

but for publish you did not define a new function and use `wait_for_publish`:
```
    message_info = c.publish("my/test/path", "Hello, world")
    await message_info.wait_for_publish()
    print("Message published!")
```

if is just an example or that's how you build it? why don't you made `await()` for both?

**Comment by mossblaser** [comment]
> why don't you made `await()` for both

Goodness knows! Good spot :). I will look into changing this when I'm not working.

> `await()` for both?

Is calling a function like this `await()` a widespread asyncio convention or just your suggestion? (I've not really used asyncio enough to have much of a feel for this kind of thing).

**Comment by mossblaser** [comment]
...so it's been a while... sorry!

Looking back at this, the main reason these interfaces differ is because paho-mqtt does it this way too: there's no convenience method for tracking subscription state. Since this module tries to be as thin a wrapper as possible it does not seem appropriate to add such a method here. slightly inconsistent as it might be.
