### ISSUE TITLE
Have you tried to do any benchmark with any other mqtt loops?

### ISSUE THREAD

**Issue by vladyslav2** [mossblaser/aiomqtt#3]
Feels like solution with asyncio is actually slower but now sure if i'm correct or not in my tests

**Comment by mossblaser** [comment]
This implementation is outrageously inefficient since my particular application (home automation type tasks) has very low throughput of messages.

If you've got experience with this kind of thing I'd be delighted to receive some PRs to improve performance to a sensible level. As the README hints, the current implementation is a bodge since in principle it should be possible to integrate the asyncio and paho-mqtt event loops 'properly'.

Are you volunteering to give this a try? :)
